
// ─────────────────────────────────────────────────────────────────────────────
// Preset configurations
// ─────────────────────────────────────────────────────────────────────────────
const PRESET_CONFIGS = {

  // ── Baseline validation preset ────────────────────────────────────────────
  example_fixed_wing: {
    aircraft: {
      empty_mass_kg:                    1.2,
      payload_mass_kg:                  0.5,
      battery_mass_kg:                  0.8,
      battery_specific_energy_wh_per_kg: 200,
      wing_area_m2:                     0.55,
      aspect_ratio:                     8.0,
      oswald_efficiency:                0.8,
      cd0:                              0.03,
      cl_max:                           1.4,
      eta_total:                        0.65,
      hotel_load_w:                     5.0,
      payload_load_w:                   10.0,
      loiter_payload_load_w:            15.0,
      peukert_exponent:                 1.0,
    },
    environment: {
      altitude_m:                       0,
      air_density_kg_per_m3:            null,
      wind_speed_m_per_s:               0.0,
      g_m_per_s2:                       9.81,
    },
    mission: {
      usable_battery_fraction:          0.9,
      reserve_energy_wh:                15.0,
      reserve_fraction:                 null,
      cruise_speed_m_per_s:             15.0,
      required_distance_km:             30.0,
      profile: {
        cruise_mode:                    "best_range",
        climb_altitude_m:               150,
        climb_rate_m_per_s:             2.0,
        outbound_distance_km:           20.0,
        outbound_altitude_m:            150,
        loiter_duration_min:            10.0,
        loiter_altitude_m:              150,
        return_distance_km:             20.0,
        return_altitude_m:              150,
        return_payload_mass_kg:         null,
        descent_altitude_m:             150,
        descent_rate_m_per_s:           2.0,
        descent_power_factor:           0.1,
        outbound_wind_speed_m_per_s:    0.0,
        return_wind_speed_m_per_s:      0.0,
      },
    },
  },

  // ── High-speed / light ────────────────────────────────────────────────────
  example_fixed_wing_fast: {
    aircraft: {
      empty_mass_kg:                    1.0,
      payload_mass_kg:                  0.3,
      battery_mass_kg:                  0.6,
      battery_specific_energy_wh_per_kg: 210,
      wing_area_m2:                     0.40,
      aspect_ratio:                     7.0,
      oswald_efficiency:                0.78,
      cd0:                              0.032,
      cl_max:                           1.3,
      eta_total:                        0.75,
      hotel_load_w:                     4.0,
      payload_load_w:                   8.0,
      loiter_payload_load_w:            8.0,
      peukert_exponent:                 1.0,
    },
    environment: {
      altitude_m:                       100,
      air_density_kg_per_m3:            null,
      wind_speed_m_per_s:               0.0,
      g_m_per_s2:                       9.81,
    },
    mission: {
      usable_battery_fraction:          0.88,
      reserve_energy_wh:                10.0,
      reserve_fraction:                 null,
      cruise_speed_m_per_s:             28.0,
      required_distance_km:             35.0,
      profile: {
        cruise_mode:                    "best_range",
        climb_altitude_m:               100,
        climb_rate_m_per_s:             2.5,
        outbound_distance_km:           25.0,
        outbound_altitude_m:            100,
        loiter_duration_min:            null,
        loiter_altitude_m:              null,
        return_distance_km:             25.0,
        return_altitude_m:              100,
        return_payload_mass_kg:         null,
        descent_altitude_m:             100,
        descent_rate_m_per_s:           2.5,
        descent_power_factor:           0.08,
        outbound_wind_speed_m_per_s:    0.0,
        return_wind_speed_m_per_s:      0.0,
      },
    },
  },

  // ── Long-range / high-AR ──────────────────────────────────────────────────
  example_fixed_wing_long_range: {
    aircraft: {
      empty_mass_kg:                    1.4,
      payload_mass_kg:                  0.4,
      battery_mass_kg:                  1.2,
      battery_specific_energy_wh_per_kg: 250,
      wing_area_m2:                     0.70,
      aspect_ratio:                     12.0,
      oswald_efficiency:                0.82,
      cd0:                              0.025,
      cl_max:                           1.5,
      eta_total:                        0.68,
      hotel_load_w:                     5.0,
      payload_load_w:                   8.0,
      loiter_payload_load_w:            12.0,
      peukert_exponent:                 1.0,
    },
    environment: {
      altitude_m:                       200,
      air_density_kg_per_m3:            null,
      wind_speed_m_per_s:               2.0,
      g_m_per_s2:                       9.81,
    },
    mission: {
      usable_battery_fraction:          0.92,
      reserve_energy_wh:                20.0,
      reserve_fraction:                 null,
      cruise_speed_m_per_s:             14.0,
      required_distance_km:             60.0,
      profile: {
        cruise_mode:                    "best_range",
        climb_altitude_m:               200,
        climb_rate_m_per_s:             1.8,
        outbound_distance_km:           40.0,
        outbound_altitude_m:            200,
        loiter_duration_min:            5.0,
        loiter_altitude_m:              200,
        return_distance_km:             40.0,
        return_altitude_m:              200,
        return_payload_mass_kg:         null,
        descent_altitude_m:             200,
        descent_rate_m_per_s:           2.0,
        descent_power_factor:           0.1,
        outbound_wind_speed_m_per_s:    2.0,
        return_wind_speed_m_per_s:      -2.0,
      },
    },
  },

  // ── Mission baseline with wind ────────────────────────────────────────────
  mission_baseline: {
    aircraft: {
      empty_mass_kg:                    1.2,
      payload_mass_kg:                  0.5,
      battery_mass_kg:                  0.8,
      battery_specific_energy_wh_per_kg: 200,
      wing_area_m2:                     0.55,
      aspect_ratio:                     8.0,
      oswald_efficiency:                0.80,
      cd0:                              0.030,
      cl_max:                           1.4,
      eta_total:                        0.65,
      hotel_load_w:                     5.0,
      payload_load_w:                   10.0,
      loiter_payload_load_w:            15.0,
      peukert_exponent:                 1.0,
    },
    environment: {
      altitude_m:                       100,
      air_density_kg_per_m3:            null,
      wind_speed_m_per_s:               3.0,
      g_m_per_s2:                       9.81,
    },
    mission: {
      usable_battery_fraction:          0.90,
      reserve_energy_wh:                15.0,
      reserve_fraction:                 null,
      cruise_speed_m_per_s:             15.0,
      required_distance_km:             30.0,
      profile: {
        cruise_mode:                    "best_wind_adjusted_range",
        climb_altitude_m:               100,
        climb_rate_m_per_s:             2.0,
        outbound_distance_km:           20.0,
        outbound_altitude_m:            100,
        loiter_duration_min:            20.0,
        loiter_altitude_m:              100,
        return_distance_km:             20.0,
        return_altitude_m:              100,
        return_payload_mass_kg:         null,
        descent_altitude_m:             100,
        descent_rate_m_per_s:           2.0,
        descent_power_factor:           0.10,
        outbound_wind_speed_m_per_s:    3.0,
        return_wind_speed_m_per_s:      -3.0,
      },
    },
  },

  // ── Loiter-heavy ISR with payload drop ────────────────────────────────────
  mission_loiter: {
    aircraft: {
      empty_mass_kg:                    1.3,
      payload_mass_kg:                  0.8,
      battery_mass_kg:                  0.9,
      battery_specific_energy_wh_per_kg: 210,
      wing_area_m2:                     0.60,
      aspect_ratio:                     9.0,
      oswald_efficiency:                0.81,
      cd0:                              0.028,
      cl_max:                           1.45,
      eta_total:                        0.66,
      hotel_load_w:                     6.0,
      payload_load_w:                   12.0,
      loiter_payload_load_w:            35.0,
      peukert_exponent:                 1.04,
    },
    environment: {
      altitude_m:                       120,
      air_density_kg_per_m3:            null,
      wind_speed_m_per_s:               1.5,
      g_m_per_s2:                       9.81,
    },
    mission: {
      usable_battery_fraction:          0.90,
      reserve_energy_wh:                18.0,
      reserve_fraction:                 null,
      cruise_speed_m_per_s:             14.0,
      required_distance_km:             25.0,
      profile: {
        cruise_mode:                    "best_range",
        climb_altitude_m:               120,
        climb_rate_m_per_s:             1.8,
        outbound_distance_km:           15.0,
        outbound_altitude_m:            120,
        loiter_duration_min:            45.0,
        loiter_altitude_m:              120,
        return_distance_km:             15.0,
        return_altitude_m:              120,
        return_payload_mass_kg:         0.3,
        descent_altitude_m:             120,
        descent_rate_m_per_s:           2.0,
        descent_power_factor:           0.10,
        outbound_wind_speed_m_per_s:    1.5,
        return_wind_speed_m_per_s:      -1.5,
      },
    },
  },

  // ── High-wind delivery with payload drop ─────────────────────────────────
  mission_windy: {
    aircraft: {
      empty_mass_kg:                    1.2,
      payload_mass_kg:                  0.6,
      battery_mass_kg:                  0.9,
      battery_specific_energy_wh_per_kg: 210,
      wing_area_m2:                     0.55,
      aspect_ratio:                     8.5,
      oswald_efficiency:                0.79,
      cd0:                              0.031,
      cl_max:                           1.4,
      eta_total:                        0.66,
      hotel_load_w:                     5.0,
      payload_load_w:                   12.0,
      loiter_payload_load_w:            12.0,
      peukert_exponent:                 1.05,
    },
    environment: {
      altitude_m:                       80,
      air_density_kg_per_m3:            null,
      wind_speed_m_per_s:               8.0,
      g_m_per_s2:                       9.81,
    },
    mission: {
      usable_battery_fraction:          0.90,
      reserve_energy_wh:                16.0,
      reserve_fraction:                 null,
      cruise_speed_m_per_s:             18.0,
      required_distance_km:             20.0,
      profile: {
        cruise_mode:                    "best_wind_adjusted_range",
        climb_altitude_m:               80,
        climb_rate_m_per_s:             2.2,
        outbound_distance_km:           12.0,
        outbound_altitude_m:            80,
        loiter_duration_min:            5.0,
        loiter_altitude_m:              80,
        return_distance_km:             12.0,
        return_altitude_m:              80,
        return_payload_mass_kg:         0.0,
        descent_altitude_m:             80,
        descent_rate_m_per_s:           2.5,
        descent_power_factor:           0.12,
        outbound_wind_speed_m_per_s:    8.0,
        return_wind_speed_m_per_s:      -8.0,
      },
    },
  },

};

// ─────────────────────────────────────────────────────────────────────────────
// Reference outputs for validation (example_fixed_wing only)
// Peukert exponent = 1.0 → factor = 1.0, so all values match prior baseline.
// ─────────────────────────────────────────────────────────────────────────────
const EXPECTED_OUTPUTS = {
  example_fixed_wing: {
    total_mass_kg:                2.5,
    stall_speed_m_per_s:          10.066631938831836,
    electrical_power_required_w:  78.25756060090337,
    still_air_range_km:           28.71476226337985,
    best_endurance: {
      airspeed_m_per_s:           11.630475743370018,
    },
    mission_profile: {
      total_energy_used_wh:       113.47263671325975,
      remaining_energy_wh:        15.127363286740247,
    },
  },
};
